### ISSUE TITLE
Change: Remove leading/trailing whitespace from strings

### ISSUE THREAD

**Issue by jschlyter** [Ixam97/CarStatsViewer#120]
Translations strings should preferably not include leading/trailing whitespace. If whitespace is needed by the UI, it should be added on use.

**Comment by jschlyter** [comment]
Strings in Lokalise stripped from leading/trailing whitespace.

**Comment by Ixam97** [comment]
Some icons and other UI elemtents will need scaling adjustments to get the same visual effect as with the whitespaces. Will adjust this before 0.23 release.
