### ISSUE TITLE
Bug: zooming on charge curve

### ISSUE THREAD

**Issue by DoubleYouEl** [Ixam97/CarStatsViewer#128]
(Dev 0.23 version 04) When zooming in on one of the recorded charge curves, then switching to another curve, the zoom settings are retained. These should better be reset to show the entire curve (which does happen when clicking anywhere within the curve area).

**Comment by Ixam97** [comment]
@boessi is there a simple way to reset the scaling and scroll of a PlotView, like `PlotView.resetScaling()`?

**Comment by boessi** [comment]
Just set the 2 values back to initial values, as this values, a reset method might be a better solution but not there ATM

**Comment by Ixam97** [comment]
Seems like `summary_charge_plot_view.dimensionShift = 0L` is enogh to reset shift and scaling. Let's see if this works with real charge curves as well. https://github.com/Ixam97/CarStatsViewer/commit/f007b9c2f0e607aa3c900f016a72dcac14a6693e

**Comment by boessi** [comment]
Only for Shift, dimensionRestriction for Zoom

**Comment by Ixam97** [comment]
Hm, at least switching from a zoomed in plot to a smaller sets the zoom to the default value. Setting `dimensionRestriction = 0L` causes the plots to be empty, `dimensionRestriction = null` fits it to the exact time, ignoring the 5min steps.

**Comment by boessi** [comment]
You have to set it to the desired distance that you want to display, like 5min / 5km (10km) etc. and not 0L/null
