### ISSUE TITLE
Feature: ABRP live data API

### ISSUE THREAD

**Issue by Ixam97** [Ixam97/CarStatsViewer#131]
It would be nice to calculate the reference consumption at 110 km/h the same way as ABRP does. 

Since ABRP does not run in the background this could be used to generate a representative value calculated over a long period of time while still being able to use other apps on the center display.

This however would require to get the exact formula from the ABRP developers to make this work as intended. I will try to reach out to them. 

Idea comes from @krheinwald

**Comment by krheinwald** [comment]
Maybe you could exchange the formula for your data collection background service? Win-win 😎

**Comment by Ixam97** [comment]
I've opened a topic in the ABRP forum. Let's see if this leads to anything:

https://forum.abetterrouteplanner.com/topic/4209-formula-to-calculate-reference-consumption/

**Comment by FreshDave29** [comment]
as there isn't even a slightest reaction from ABRP-staff, maybe we go ahead and try to solve it on our own?

My suggestion would be to implement a rolling average function, that keeps track of all consumption values, that occur during a xx second cruise on speeds between 105-115 km/h.
Outliers of +- 50% (e.g. of a target of 18kWh/100km) should be omitted, as they most likely are results of heavy acceleration/deceleration.

**Comment by krheinwald** [comment]
Let me give it a try with my personal contact from the PS port.

**Comment by Ixam97** [comment]
Katya has responded to my forum post yesterday. They will not give me direct access to the calculations, but suggested to use the telemetry API. I Will have a look into it but it seems like this would allow to directly feed live data into your own ABRP account without requiring the ABRP-app on the car.

**Comment by Ixam97** [comment]
I have now implemented the ABRP live data API into CSV. This allows the user to constantly send data to the ABRP-Servers, where they are stored for later view and to calculate the reference consumption without the need to have ABRP nor CSV in the foreground of the infotainment system.

This also lays the ground work for a simple system to integrate other APIs to send live data.

**Comment by BeauGiles** [comment]
What's the best way to apply for an API key from ABRP and what exactly are we asking for from ABRP to get this up in running from Car Stats Viewer?

**Comment by BeauGiles** [comment]
Disregard, found it!
Instructions for anyone else looking for this 'Generic Token', no need to request API access or anything from ABRP.

Open ABRP or https://abetterrouteplanner.com
Click on ABRP logo/menu on top left
Under 'Plan Settings', tap on vehicle
Tap on 'Edit Settings'
Under 'Over-the-air live data', next to "No live data linked", tap on "Add Live Data"
Tap on 'Link Generic'.
Take note of the loooong token.

Enter this token into Ca rStats Viewer.
Done!

**Comment by Ixam97** [comment]
>Take note of the loooong token.
>
>Enter this token into Car Stats Viewer.

You could also just open the ABRP app in the car and copy/paste the token ;)
