### ISSUE TITLE
Bug: default trip summary type not visible in settings page

### ISSUE THREAD

**Issue by DoubleYouEl** [Ixam97/CarStatsViewer#133]
In 0.23 dev 5 (and already earlier), the settings page doesn’t show the text anymore for the default trip summary type (automatic, last month, …)

![11887A8C-8A3F-4FA5-98D4-194145C5CFC9](https://user-images.githubusercontent.com/11661560/221187963-9f52d6fd-74d5-4e83-8e30-ab2125bc8769.jpeg)

**Comment by Ixam97** [comment]
See #132

**Comment by DoubleYouEl** [comment]
0.23_rc01 is indeed correct, so this issue can be closed

![16299BB2-BFF0-4A63-A98F-382470DC3B71](https://user-images.githubusercontent.com/11661560/221263710-69d127df-c30a-4341-813f-a848b5093398.jpeg)
