### ISSUE TITLE
Installation GPS bug?

### ISSUE THREAD

**Issue by StefanH1969** [Ixam97/CarStatsViewer#134]
direkt nach der Installation war das GPS Signal für Google Maps nicht mehr zu finden. den Fehler hatte ich die letzten 12 Monate etwa sechs mal von daher kann es auch Zufall sein. allerdings hatte die App direkt zuvor die GPS abgefragt und bekommen von daher ist meines Erachtens auch ein Zusammenhang denkbar. Nach TCAM -Reset läuft alles prima. vielen Dank!

**Comment by FreshDave29** [comment]
Hi Stefan,
derzeit sind ca 400-500 Installationen im Umlauf, würde die App das GPS blocken, wäre es bestimmt schon aufgefallen.
Tatsächlich erfragt CSV die GPS-Berechtigung, sammelt aber keine Daten mehr im Hintergrund (dazu müssten wir recht aufwändige Google-Regularien erfüllen).
Ziel der Implementierung war es das Höhenprofil für die gefahrene Strecke zu bekommen, um mehr Kontext für den Verbrauch zu schaffen. 
Das Ganze ist derzeit noch Work in Progress.
Wenn ein TCAM-Reset den Fehler behebt und sich CSV danach normal ausführen lässt, würde ich erstmal keinen direkten Zusammenhang sehen.

**Comment by Ixam97** [comment]
Da ich bisher auch weder selber das Problem hatte, noch von wem anderes davon gehört habe, denke ich nicht, dass es hier einen Zusammenhang mit der Installation vom CSV gibt. Sollte das Verhalten doch wieder auftreten, bitte melden.
