### ISSUE TITLE
Ladekabelstatus - Anzeige überflüssig?

### ISSUE THREAD

**Issue by marky5525** [Ixam97/CarStatsViewer#16]
Ich finde die Anzeige des Ladekabelstatus überflüssig. Ja, es ist schön, wenn man es sehen kann, aber wozu? In der Regel benutze ich die App ja während der Fahrt, und da weiß ich, dass kein Ladekabel angeschlossen sein kann.

Dass man die Variable nutzt, um irgendwann die Ladekurve aufzuzeichnen (Umschaltung der Anzeige, wenn Ladekabel = true) kann ja sein, aber als Anzeige braucht man das doch nicht, oder?

TI würde sagen: "I don't feel it"

**Comment by Ixam97** [comment]
Die Anzeige für das Ladekabel wird in Zukunft nicht mehr sichtbar sein.

Wenn der Ladekurven-Plot implementiert ist, dann wird zwischen Verbrauchskurve und Ladekurve umgeschaltet, je nach dem, ob das Kabel angeschlossen ist oder nicht.
