### ISSUE TITLE
Bug: Some States of Charge are skipped

### ISSUE THREAD

**Issue by Ixam97** [Ixam97/CarStatsViewer#161]
Some States of Charge are skipped because of rounding Float to Int.

```
55.0 %
54.000004 %
52.999996 %
52.0 %
```

The reason for these minimal errors is unknown. Changing `toInt()` to `roundToInt()` should make this a non-issue.

**Comment by Ixam97** [comment]
With the help of some logs by @krheinwald I found some more strange SoC-values, especially in the lower regions:

```
0.19
0.19799998
0.19
0.18
0.17
0.161
0.16
0.158
0.15100001
0.15
0.142
0.141
0.14
0.133
0.132
0.13100001
0.13
0.123
0.121999994
0.12100001
0.12
0.118
0.115
0.113000005
0.111999996
0.111
0.11
0.105
0.103
0.102
0.101
0.1
0.098000005
0.096999995
```

It looks like the SoC gets a much higher resolution in the lower regions. Howerver the steps are not consistent at all and I still cant make any sense of those odd values.

This should not be of concern since the SoC used in CSV is now rounded to whole numbers.

**Comment by CONSULitAS** [comment]
@Ixam97 

Why not round to one decimal precision first (eg. 9.4 %) and show SOC with this precision when below 10%?
