### ISSUE TITLE
Feature: slow down send interval to ABRP when errors occur

### ISSUE THREAD

**Issue by CONSULitAS** [Ixam97/CarStatsViewer#177]
Errors like this could point to congestion at ABRP which should be gracefully avoided:

```
07.07.2023 12:54:51.781 E: [ABRP] Network timeout error
```

Solution: adapt send interval dynamically, but
* try at least once a minute
* send no more than every 5 seconds

**Comment by CONSULitAS** [comment]
> * send no more than every 5 seconds

from API description

> The desired data rate is one point every 5 seconds, but slower rates are accepted. Less than one every 30 seconds is recommended against.

So I would suggest:
* try at least once a minute
* when  transmission successful lower interval for next transmission
  * to 30 seconds when >30 seconds
* when at least 5 successful transmissions lower interval for next transmission
  * by 5 seconds

**Comment by CONSULitAS** [comment]
If the car is offline, the send interval should not be changed.

Perhaps here is a way to detect?

**Comment by Ixam97** [comment]
> If the car is offline, the send interval should not be changed.

I've now limited timeout increases to only occure on timeout exceptions. All other connection errors do not increase the interval.
