### ISSUE TITLE
Feature: colour match between graph and axis labels

### ISSUE THREAD

**Issue by DoubleYouEl** [Ixam97/CarStatsViewer#182]
It would be nice if the orange graph would also have orange axis labels on the vertical axis. E.g. in the attached screen shot, the power curve is orange, but its labels on the left are white (except for the average value in the box). It would take less mental load if colours always matched.

[Note: I thought this was already reported before, but I cannot find it in the issues. Perhaps it's part of a broader topic...]

![image](https://github.com/Ixam97/CarStatsViewer/assets/11661560/47c4c8c3-5169-4508-893e-06dad80f85e5)

**Comment by Ixam97** [comment]
I have tested this already a while ago and came to the conclusion that it hurts visibility more than it helps. So I will not add this. I think for now the position of the avg. labels is enough to clarify the meaning of each axis. 

But I am planing to do some visual changes on the main view in the future.
