### ISSUE TITLE
0.25.1 (Dev) repeatedly restarted during long trip

### ISSUE THREAD

**Issue by DoubleYouEl** [Ixam97/CarStatsViewer#190]
I’m running the Dev version 0.25.1, which repeatedly restarted yesterday during a long trip (between 500 and 600 kms). Maxi, I sent you the log file and recent trips.
Note that the bug opening the empty charging session also still crashes the app. My second log file sent today (without trips) is just after that crash happened.

**Comment by Ixam97** [comment]
> Note that the bug opening the empty charging session also still crashes the app. My second log file sent today (without trips) is just after that crash happened.

Yes, you are right, I made a little mistake there 🙃

Regarding the other crashes there are sadly no crash reports in the log. The app just terminates without a caught exception. So it is very hard for me to track this down. But it seems fine after the center display reboot. Can you please send the log again in with logging level set to verbose?

Also: Was the charging curve at 14:07 recorded correctly? I see a lot of `Power value too old` there.

**Comment by Ixam97** [comment]
@DoubleYouEl Has this occured again with the newer versions? For me the App is running very stable and I have not heard of any reports regarding repeated crashes.

**Comment by DoubleYouEl** [comment]
@Ixam97 No, this doesn't happen any more since a few (intermediate) updates ago. So it seems safe to close this issue...
