### ISSUE TITLE
Angeforderte und Gelieferte Ladeleistung

### ISSUE THREAD

**Issue by Nartens** [Ixam97/CarStatsViewer#197]
Es wäre schön zu wissen wenn der Polestar z.150KW an der Ladestation anfordert aber aufgrund einer Leistungsbegrenzung auf Seiten der Ladeinfrastruktur nur 100KW erhält.

**Comment by Ixam97** [comment]
Ich kenne aktuell keine Möglichkeit, diese Informationen auszulesen.
