### ISSUE TITLE
Webhooks - Definitive List

### ISSUE THREAD

**Issue by sembeeuk** [Ixam97/CarStatsViewer#198]
Is there a definitive list of what is exposed using the webhooks and their values? I have seen various entries in the forums, but there doesn't seem to be anywhere with a complete list.

Thanks.

**Comment by Ixam97** [comment]
The Webhook API gets extended quite a bit with the next update. I will try to also provide a little documentation on how it works and what values are provided in some time.

**Comment by Ixam97** [comment]
In the meantime you can have a look at this file. It's the basis to generate the json output. Nullable values are optional.

[HttpDataSet.kt](https://github.com/Ixam97/CarStatsViewer/blob/master/automotive/src/main/java/com/ixam97/carStatsViewer/liveDataApi/http/HttpDataSet.kt)

**Comment by sembeeuk** [comment]
Using the webhook.site I was able to get this list:

{
  "alt": x,
  "ambientTemperature": 16,
  "apiVersion": 2,
  "appVersion": "0.25.1.0011",
  "batteryLevel": 59496,
  "chargePortConnected": false,
  "ignitionState": "On",
  "lat": X,
  "lon": x,
  "power": 850000,
  "selectedGear": "P",
  "speed": 0,
  "stateOfCharge": 0.74,
  "timestamp": x
}

Just need to work out the units.
Speed appears to be m/s
State of Charge needs multiplying by 100 to get the percentage. 
Haven't worked out what power is yet - milliwatts maybe?

Thanks for the excellent app.

**Comment by Ixam97** [comment]
Have a look at this: https://github.com/Ixam97/CarStatsViewer/blob/master/docs/APIDOC.md
