### ISSUE TITLE
Feature: Auto reset trip on certain conditions

### ISSUE THREAD

**Issue by FreshDave29** [Ixam97/CarStatsViewer#2]
Reset der Daten nach bspw. 4h Standzeit, analog Bordcomputer

**Comment by Ixam97** [comment]
Ich denke ich werde eine Einstellung einbauen, in der man mit einem Slider selber festlegen kann, nach welcher Zeit ein automatischer Reset stattfinden soll.

**Comment by DoubleYouEl** [comment]
This would be indeed a good change of functionality

**Comment by Ixam97** [comment]
Im currenty working on implementing four seperate data trackers collecting data at the same time. Each tracker has different reset conditions:
- Reset after charging (keeping the last charging session for late view)
- Reset after 4 h of parking
- Reset at the beginning of every month (and saving the last one)
- Manual reset as konwn

**Comment by Ixam97** [comment]
These four trackers have now been implemented and will be released with the next update: https://github.com/Ixam97/CarStatsViewer/commit/9353d9821a7ad24761418f514a32dbb366262480

For now, only the current trackers can be viewed. Viewing older trips will be added in the future, see https://github.com/Ixam97/CarStatsViewer/issues/46
