### ISSUE TITLE
Feature: Battery information

### ISSUE THREAD

**Issue by kyuzumaki** [Ixam97/CarStatsViewer#217]
Is it possible to read out and display any battery information from the BMS? Would be really useful to be able to see module voltages, charge cycles, etc. It must all be in there already. I saw one comment mentioning temperature wasnt available so possibly not accesable from the android part of the car directly..

If not accesable via android directly would a bluetooth ODB II adapter be able to read that info out?

**Comment by Ixam97** [comment]
Hi,

Via Android it is not possible to get any data from the BMS except for the SOC and the current power draw.

I'm not familiar with ODB-Dongles, but it may be possible to use one. I'm not sure though if it would be possible to directly connet it to the cars Android system.

**Comment by ivanfmartinez** [comment]
@Ixam97 for reference this code worked fine on Bolt EV to get information, never checked what standard PIDs are available on Volvo, and I never seem public list of volvo PIDs.

https://github.com/traccar/traccar-client-android/compare/master...ivanfmartinez:traccar-client-android:ivanfm-changes

If we have access to PIDs list the integration with OBD is the easiest part .

**Comment by Ixam97** [comment]
I'm currently not planing on adding any support for external devices. But I might look into it later if someone else does the ground work.
