### ISSUE TITLE
Bug: CarStatsViewer is unable to start with P3.0.3

### ISSUE THREAD

**Issue by jkkataja** [Ixam97/CarStatsViewer#221]
Hi,

I received P3.0.3 to my car yesterday. After installing the update, CSV fails to start. Upon attempting to start the app the screen returns to start screen (4 tiles) without displaying anything after couple of seconds.

Will happily debug as per instructions.

Cheers

**Comment by sven-petersen** [comment]
Just curious but do you already have the recent version of CSV ([0.26.1](https://github.com/Ixam97/CarStatsViewer/releases/tag/v0.26.1))? There was a fix/change to make it supposedly work with P3.0.3/Android 12.

**Comment by jkkataja** [comment]
Seems to be older version I reckon
![20240425_171206](https://github.com/Ixam97/CarStatsViewer/assets/42151530/9b935d53-f7a6-4ba8-8950-24ec4901435c)

**Comment by jkkataja** [comment]
Old version of CSV running.

**Comment by klillevo** [comment]
I have the same issue, but I am unable to find any updates. No updates available in the car for carstatsviewer, and unable to check for updates on Google Play with the account I signed up for testtrack. It will probably update itself eventually....

**Comment by sven-petersen** [comment]
> I have the same issue, but I am unable to find any updates. No updates available in the car for carstatsviewer, and unable to check for updates on Google Play with the account I signed up for testtrack. It will probably update itself eventually....

(More as a info for potentially other people finding this issue:)

The maintainer of your test track has to update the app which usually is a (partially) manual process. So you can try asking him/her if he can update the track, open your own test track if you have a google dev account or look for another track which is already up to date.

**Comment by DoubleYouEl** [comment]
You can always check the current version for all test tracks here:
https://polestar.fans/t/carstatsviewer-informationen/15027

Currently, all test tracks are up to date (0.26.1)

**Comment by jkkataja** [comment]
> You can always check the current version for all test tracks here: https://polestar.fans/t/carstatsviewer-informationen/15027
> 
> Currently, all test tracks are up to date (0.26.1)

Did you update your track recently? Or is my screenshot really showing version 0.26.1? I.e., how should those zeroes be interpreted?

**Comment by klillevo** [comment]
My testtrack is unlisted, but I have asked the developer if it can be updated to 0.26.1 as well. Thanks.
com.coderax.carStatsViewer_dev
https://play.google.com/apps/internaltest/4698289242746853179

**Comment by Ixam97** [comment]
@jkkataja Yes, the last of the tracks I know of has updated yesterday. So it should be fixed for everyone now. 

The last number in the version number is the Build. I generally count that up once I install a Dev version on my own car. So, 0.26.0 went through 10 iterations of me installing it on my car before pushing the changes to master.

@klillevo If a track is not listed in the german forums' list, I can't really provide any help. I am in regular contact with those maintainers. So they get notified right away when updates are released and something changed in the build process. Also the API Key for the ABRP-Integration is not publicly available.

**Comment by DoubleYouEl** [comment]
> > You can always check the current version for all test tracks here: https://polestar.fans/t/carstatsviewer-informationen/15027
> > Currently, all test tracks are up to date (0.26.1)
> 
> Did you update your track recently? Or is my screenshot really showing version 0.26.1? I.e., how should those zeroes be interpreted?

Yes, I updated it shortly before adding the above replay here on GitHub.

**Comment by klillevo** [comment]
@Ixam97 Thank you. I am pretty new to CarStatsViewer, and was not even aware Coderax build is a fork until now. He provides intergration with Homey and a Homey app, which is what I need. I don't need abrp integration and don't know if it works or not in the version I have installed.
