### ISSUE TITLE
Feature: Android Automotive Widget

### ISSUE THREAD

**Issue by dgomes** [Ixam97/CarStatsViewer#226]
It would be great to include information from CarStatsViewer at the widget level:

![3-2](https://github.com/Ixam97/CarStatsViewer/assets/137684/3f0f643a-b0fc-48ab-8792-01c9700f1aee)

The information that shows in the notification (which is usually hidden) should be shown in the widget

**Comment by Ixam97** [comment]
Duplicate of #76
