### ISSUE TITLE
Possibilty for setting Legacy display as default starting up display with ciffers and graphics as we are used to last year.

### ISSUE THREAD

**Issue by agdejager** [Ixam97/CarStatsViewer#235]
Possibilty for setting Legacy display as default starting up display with ciffers and graphics as we are used to last year.

The new starting up display is very very dull and the legacy display is gone the next time the CSV app is started again.

**Comment by Ixam97** [comment]
This is not possible when using the templates. You can launch the App from the notification to go directly to the legacy dashboard. Keep in mind it will not be visible while driving.
