### ISSUE TITLE
Design: Anpassung Farben an Polestar-Standard

### ISSUE THREAD

**Issue by marky5525** [Ixam97/CarStatsViewer#24]
Für Menschen wie mich mit Grün-Schwäche wäre in der Tat der Polestar-Standard an Farben nice to have.

**Comment by Ixam97** [comment]
69c0296cc3d0f521489f24c381ed5eef71617782

Mit dem nächsten Update wird man zwischen grau und grün als sekundäre Diagrammfarbe wählen können.
