### ISSUE TITLE
Graphen außerhalb der Skala

### ISSUE THREAD

**Issue by marky5525** [Ixam97/CarStatsViewer#37]
Version 0.19 @boessi 
Die Graphen liegen weiterhin außerhalb der Skala und sind in den unterschiedlichen Ansichten (5, 15, trip) unterschiedlich.
So war mir heute morgen aufgefallen, dass bei 15km der Graph passt, beim Umschalten auf 5km aber außerhalb der Skala bricht.
Ebenso wurde bei Trip die Skala verlassen.

Ist es Absicht, dass die Skala nur bis 90 kW und -30 kW zeigt oder sollte die skalieren?

**Comment by boessi** [comment]
Das ist bewusst so implementiert und ein Feature. Das definierte Min/Max gilt dann als die Grenze für das zeichnen.

**Comment by Ixam97** [comment]
> So war mir heute morgen aufgefallen, dass bei 15km der Graph passt, beim Umschalten auf 5km aber außerhalb der Skala bricht.

Das ist ebenfalls gewolltes verhalten. Damit die Diagramme nicht unlesbar werden, werden maximal 50 Datenpunkte angezeigt. Also bei 5km alle 100m ein Punkt, bei 15km alle 300m. Dafür werden dann die innerhalb dieser Distanz erfassten Werte auf diese Strecke gemittelt. So kann es passieren, dass Peaks bei einer größeren Distanz weniger hoch sind.

Da sich die Leistung sehr schnell und stark ändert, ist eine Darstellung ohne Glättung kaum praktikabel. Ziel ist es solche Anblicke zu vermeiden: https://polestar.fans/t/car-stats-viewer-bordcomputer-aber-viel-besser/14091/225

Die Werte für die Maximalwerte der Achsen und der Glättung sind noch nicht endgültig. Ich möchte damit aber erst mal etwas Erfahrung sammeln, um beurteilen zu können, welche Werte sinnvoll sind.
