### ISSUE TITLE
Change: Reduce flickering in power gauge

### ISSUE THREAD

**Issue by FreshDave29** [Ixam97/CarStatsViewer#54]
To reduce disturbance and flickering in the power gauge, the decimals should be omitted on values e.g above 10 kW

**Comment by FreshDave29** [comment]
see #55

**Comment by Ixam97** [comment]
[6a9a4ae](https://github.com/Ixam97/CarStatsViewer/commit/6a9a4aeb2148cfeb8cb705307bfacdb3c7944365)

**Comment by Ixam97** [comment]
Released in [v0.21.0](https://github.com/Ixam97/CarStatsViewer/releases/tag/v0.21.0)
