### ISSUE TITLE
Feature: Unit Swap and/or Detection

### ISSUE THREAD

**Issue by kdagnan** [Ixam97/CarStatsViewer#74]
Hi,

I’m based in the US and therefore used to imperial units (terrible, I know). kWh/100 miles primarily but any others that may be in there.

I’d be interested in attempting implementation if it’s not already available or in the works.

**Comment by Ixam97** [comment]
Im not planing on implementing "freedom units" myself 😜

If you want to you can give it a try. In general you would just need to use a factor on the values when generating the Strings. Im currently working on a bigger rework of the internal data structure, but these functions should not be affected too much.

Short example for the speed string:
```
    private fun getCurrentSpeedString(): String {
        when (unitSystem) {
            UnitSystem.Imperial -> return "${(DataHolder.currentSpeedSmooth * 2.236).toInt()} mph"
        }
        return "${(DataHolder.currentSpeedSmooth * 3.6).toInt()} km/h"
    }
```

The display distance unit can also be read from the VHAL: https://developer.android.com/reference/android/car/VehiclePropertyIds#DISTANCE_DISPLAY_UNITS

**Comment by casey-hillman** [comment]
I'm a dirty American as well and would like to see this implemented. I was wondering if there was a way to link the displayed units to what the System Units setting is.

**Comment by boessi** [comment]
will have a look, we might noot change how we collect and store the data but as @Ixam97 suggested we can use the label functions and the system settings to convert the values. Also the plot need to be adjusted.

will wait for the reworked data manager to implement it

**Comment by Ixam97** [comment]
With this miles and km can be toggled manually. I'll have a look at switching it depending on the system setting.
