### ISSUE TITLE
Displayed Distance does not match

### ISSUE THREAD

**Issue by MicPra** [Ixam97/CarStatsViewer#8]
The displayed traveled distance does not correspond to the real traveled distance.  In my case, with 79 km traveled, about twice as much as 140km was displayed.  The App was restarted before (forced stop)

**Comment by Ixam97** [comment]
I suspect some problems with how services were implemented in the app aus the cause of this. Instead of `startService()` the app now uses `startForegroundService()`. This should make data collection more reliable and hopefully solve this bug.

**Comment by marky5525** [comment]
I don't get this bug anymore. Vote for close.
