### ISSUE TITLE
Change: Lower refresh rate for power gauge

### ISSUE THREAD

**Issue by DoubleYouEl** [Ixam97/CarStatsViewer#81]
Currently the power gauge is refreshed many times per second (maybe even at frame rate - hard to tell). It seems more useful to have a slightly slower update rate, with data averaged over a small window in time, instead of instantaneous refresh.

**Comment by Ixam97** [comment]
In the next version the main view will update once a second. This also affects the gages.
However, to quickly respond to large Value changes, the gages will update independently if the delta is larger than 1 kW or 10 Wh/km. I think that's a good compromise between fast updates and not updating too much when it's not needed.
